### ISSUE TITLE
Hard-code file paths are a no-no

### ISSUE THREAD

**Issue by ldemaz** [agroimpacts/arcticdynamics#1]
Use relative paths for reproducibility....

https://github.com/agroimpacts/Artic-Cloud-Change-Dynamics/blob/098a4e99ab66bdc76d27fbd8ecfd02d6f4775a95/vignettes/overview.Rmd#L74

**Comment by ldemaz** [comment]
https://github.com/agroimpacts/Artic-Cloud-Change-Dynamics/blob/098a4e99ab66bdc76d27fbd8ecfd02d6f4775a95/vignettes/overview.Rmd#L137

**Comment by CGaffey** [comment]
It's to the netCDF which we can't upload to github because it's too big. How could I better refer to that file?

**Comment by ldemaz** [comment]
Relative file paths, so an untracked directory within your project folder, e.g. `external/data`, and then:

```
ppath <- here::here("external/data/")
```

**Comment by ldemaz** [comment]
If the dataset is not shareable on the repo, you need to set the chunk to `eval=FALSE` also, and save intermediate, lighter-weight outputs that can be used in downstream chunks.

**Comment by CGaffey** [comment]
Okay, and then would I put a placeholder in the "external/data" folder that is a text doc or something that says "for the dataset used, download via NARR / Earthdata / etc..."?
